
services:
  &app s63:
    labels:
      - "traefik.http.routers.s63.rule=Host(`s63.127.0.0.1.sslip.io`)"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: "1"
      # target: run # builder
      platforms:
      - linux/arm64
      tags:
      - nicolas/s63:rpi3
      cache_from:
      - type=local,src=./.cache
      cache_to:
      - type=local,dest=./.cache,mode=max
    platform: linux/arm64
    image: nicolas/s63:rpi3
    container_name: *app
    network_mode: bridge
    entrypoint: ["/bin/bash", "-c", "while true; do node src/index.js; sleep 10; done"]
    develop:
      watch:
        - action: sync
          path: ./code/src
          target: /app/src
        # - action: rebuild
        #   path: ./app_web/requirements.txt
        #   target: /app/requirements.txt